const fs=require('node:fs');
const path=require('node:path');
const ROOT=__dirname;
const data=fs.existsSync(path.join(ROOT,'chiffres.json')) ? JSON.parse(fs.readFileSync(path.join(ROOT,'chiffres.json'))) : {savings:'3 058 072',partners:'51',managed:'100',year:'2026'};
const PROD=globalThis.process.env.GP_PROD==='1';
const OUT=globalThis.process.env.GP_OUT||ROOT;// dossier de sortie des pages HTML (la maquette par défaut)
if(OUT!==ROOT)fs.mkdirSync(OUT,{recursive:true});
const proof=require(path.join(ROOT,'social-proof.cjs'))(ROOT,data);
const perSimulator=fs.readFileSync(path.join(ROOT,'per-simulator.html'),'utf8');
const lifeSimulator=fs.readFileSync(path.join(ROOT,'life-simulator.html'),'utf8');
const insuranceSimulator=fs.readFileSync(path.join(ROOT,'insurance-simulator.html'),'utf8');
const perHero=`<span class="small-caps">Votre PER, simplement</span><h2>Et si vous faisiez<br>le calcul ?</h2><p>Quelques questions pour estimer votre économie d’impôt et vous projeter.</p><ol class="per-hero-steps"><li><span>1</span>Votre situation</li><li><span>2</span>Vos informations fiscales</li><li><span>3</span>Votre versement</li></ol><a class="button button-gold" href="#simuler">Commencer ma simulation <span aria-hidden="true">→</span></a><p class="fine-print">Résultat immédiat · Sans coordonnées à renseigner</p>`;
const lifeHero=`<span class="small-caps">Faites grandir vos projets</span><p class="life-hero-capital" data-life-capital>—</p><p class="life-hero-label">de capital projeté dans <span data-life-horizon>20 ans</span></p><svg id="life-hero-chart" viewBox="0 0 440 115" role="img" aria-label="Aperçu de l’évolution simulée du capital"></svg><p class="life-hero-caption" data-life-hero-assumptions>Personnalisez votre projection en quelques gestes.</p><a class="button button-gold" href="#simuler-assurance-vie">Tester mon scénario <span aria-hidden="true">↗</span></a><p class="life-hero-note">1 % de frais sur versements intégrés. Projection non garantie, avant fiscalité et prélèvements sociaux.</p>`;

const icons={
 arrow:'<path d="M4 12h15M13 6l6 6-6 6"/>',
 shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z"/><path d="m8.5 12 2.5 2.5 4.5-5"/>',
 chart:'<path d="M4 20V9m6 11V4m6 16v-7m5 7H2"/>',
 growth:'<path d="M12 21V11M12 15C5 15 3 11 3 6c6 0 9 3 9 9Zm0-4c0-6 3-9 9-9 0 6-3 9-9 9Z"/>',
 umbrella:'<path d="M3 12a9 9 0 0 1 18 0H3Zm9 0v7a2 2 0 0 0 4 0M12 3V1"/>',
 heart:'<path d="M20.8 4.6a5.6 5.6 0 0 0-7.9 0l-.9.9-.9-.9a5.6 5.6 0 0 0-7.9 7.9L12 21l8.8-8.5a5.6 5.6 0 0 0 0-7.9Z"/><path d="M5.5 12H9l2-4 2 8 2-4h3.5"/>',
 balance:'<path d="M12 3v18M8 21h8M4 7l8-3 8 3M4 7 1 14h6L4 7Zm16 0-3 7h6l-3-7Z"/>',
 check:'<path d="m5 12 4 4L20 5"/>',
 play:'<path d="m9 5 11 7-11 7V5Z" fill="currentColor" stroke="none"/>',
 phone:'<path d="m5 3 4 1 1 5-3 2a15 15 0 0 0 6 6l2-3 5 1 1 4c0 2-3 3-5 2C8 19 5 16 3 8 2 6 3 3 5 3Z"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 person:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-3a8 8 0 0 1 16 0v3"/>',
 doc:'<path d="M14 2H5v20h14V7l-5-5Zm0 0v5h5M8 12h8M8 16h6"/>',
 book:'<path d="M12 5C8 2 4 3 2 4v16c3-1 6-1 10 1 4-2 7-2 10-1V4c-2-1-6-2-10 1Zm0 0v16"/>',
 close:'<path d="m6 6 12 12M18 6 6 18"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.shield}</svg>`;
const services=[
{slug:'assurance-emprunteur',name:'Assurance emprunteur',short:'Assurance emprunteur',icon:'shield',sentence:'Réduisez le coût de votre crédit.',headline:'Votre crédit reste.<br>Le coût de votre assurance <em>diminue.</em>',intro:'Comparez votre assurance de prêt avec un courtier indépendant. Je prends en charge les démarches, de l’étude à la mise en place.',cta:'Étudier mon assurance',benefits:[['Votre banque reste la même','Le changement porte sur votre assurance de prêt.'],['Des garanties comparées','Une étude attentive de l’équivalence des garanties.'],['Les démarches prises en charge','Un interlocuteur unique jusqu’à la mise en place.']],explain:'Une meilleure assurance, sans changer de banque.',body:'La loi Lemoine permet de changer d’assurance emprunteur à tout moment pour les prêts concernés. Nous comparons les contrats, vérifions les garanties et préparons votre dossier.',faq:[['Dois-je contacter ma banque moi-même ?','Non. Je m’occupe de toutes les formalités administratives, y compris de la résiliation de votre ancien contrat.'],['Les garanties sont-elles conservées ?','L’équivalence des garanties demandées par votre banque est vérifiée avant toute mise en place.'],['Combien puis-je économiser ?','Le résultat dépend de votre prêt, de votre profil et de votre contrat actuel. L’étude permet de chiffrer votre économie potentielle.']]},
{slug:'per',name:'Plan Épargne Retraite',short:'PER & Retraite',icon:'chart',sentence:'Préparez votre retraite et optimisez votre fiscalité.',headline:'Préparez votre retraite.<br>Donnez du sens à <em>votre épargne.</em>',intro:'Faites le point sur votre situation fiscale et votre épargne. Une étude personnalisée pour savoir si le PER correspond à vos objectifs.',cta:'Demander ma simulation',benefits:[['Une fiscalité étudiée','Vos possibilités de déduction selon votre situation.'],['Une épargne pour demain','Un horizon et des supports adaptés à votre profil.'],['Un accompagnement complet','Du choix du contrat au suivi de votre PER.']],explain:'Comprendre avant de choisir.',body:'Le PER est une épargne de long terme conçue pour la retraite. Nous étudions ensemble les versements, les frais, les supports, les possibilités de sortie et la fiscalité associée.',faq:[['Comment se déroule la simulation ?','Le simulateur permet de tester votre versement avec vos données. Nous pouvons ensuite vérifier ensemble votre avis d’impôt, votre plafond disponible et vos objectifs pour établir une étude personnalisée.'],['Mon épargne est-elle disponible à tout moment ?','Le PER est destiné à la retraite. Des cas de déblocage anticipé existent, notamment l’achat de la résidence principale pour certains versements. Ils sont étudiés selon votre situation.'],['Peut-on étudier un PER que je possède déjà ?','Oui. Nous pouvons comparer ses frais, ses supports et ses conditions avec vos objectifs actuels.']]},
{"slug": "assurance-vie", "name": "Assurance-Vie", "short": "Assurance-Vie", "icon": "growth", "sentence": "Faites grandir votre épargne et préparez vos projets.", "headline": "Votre épargne, aujourd’hui.<br><em>Vos projets, demain.</em>", "intro": "Construisez une épargne qui correspond à vos objectifs. Je vous accompagne pour comparer les contrats d’assurance-vie, comprendre les frais et choisir des supports adaptés à votre profil.", "cta": "Parlons de mon épargne", "benefits": [["Vos projets", "Constituer une épargne pour vos objectifs, à votre rythme."], ["Votre profil", "Étudier les supports selon votre horizon et votre sensibilité au risque."], ["Vos proches", "Réfléchir à la désignation de vos bénéficiaires et à votre situation familiale."]], "explain": "Un contrat. Plusieurs projets de vie.", "body": "L’assurance-vie permet de constituer une épargne investie sur différents supports. Nous étudions ensemble les fonds en euros, les unités de compte, les frais, les possibilités de retrait et la clause bénéficiaire.", "faq": [["Mon épargne est-elle bloquée pendant huit ans ?", "Non. Un retrait, appelé rachat, est possible selon les conditions du contrat. L’ancienneté de huit ans correspond à un seuil fiscal, pas à une durée de blocage."], ["Le capital est-il garanti ?", "Le fonds en euros bénéficie d’une garantie de l’assureur, selon les conditions du contrat. Les unités de compte ne garantissent pas le capital : leur valeur peut baisser."], ["Puis-je verser à mon rythme ?", "Selon le contrat, vous pouvez effectuer des versements ponctuels ou programmés. Les montants minimums et les modalités sont à vérifier."], ["Pouvez-vous étudier mon assurance-vie actuelle ?", "Oui. Nous examinons ses frais, ses supports, son ancienneté et sa clause bénéficiaire avant d’envisager une évolution."], ["Comment préparer la transmission ?", "La clause bénéficiaire désigne les personnes qui recevront le capital en cas de décès. Sa rédaction et la fiscalité applicable s’étudient selon votre situation."]]},
{slug:'prevoyance',name:'Prévoyance',short:'Prévoyance',icon:'umbrella',sentence:'Protégez vos revenus et votre famille.',headline:'Votre activité compte.<br><em>Votre protection aussi.</em>',intro:'Anticipez les conséquences d’un arrêt de travail, d’une invalidité ou d’un décès avec une protection étudiée pour votre situation.',cta:'Faire le point sur ma protection',benefits:[['Vos revenus','Identifier les besoins en cas d’arrêt d’activité.'],['Votre famille','Étudier la protection de vos proches.'],['Votre profession','Tenir compte de votre statut et de vos garanties.']],explain:'Une protection à votre mesure.',body:'Nous faisons le point sur votre couverture existante, vos charges et vos besoins pour comparer les garanties utiles, leurs limites et leurs conditions.',faq:[['À qui s’adresse cette étude ?','Aux personnes qui souhaitent mieux comprendre leur protection et celle de leurs proches, notamment les indépendants et les professions libérales.'],['Puis-je conserver mon contrat actuel ?','L’étude commence par vos garanties actuelles. Un changement n’est envisagé que s’il correspond à vos besoins.'],['Quels éléments préparons-nous ensemble ?','Votre statut professionnel, vos revenus, vos charges et les garanties déjà en place.']]},
{slug:'mutuelle',name:'Mutuelle',short:'Mutuelle',icon:'heart',sentence:'Une couverture santé adaptée à votre situation.',headline:'Votre santé d’abord.<br>Une couverture <em>qui vous correspond.</em>',intro:'Trouvez un équilibre entre vos besoins de santé, vos garanties et votre budget, avec un accompagnement personnel.',cta:'Étudier ma couverture santé',benefits:[['Vos besoins réels','Optique, dentaire, hospitalisation et soins courants.'],['Votre budget','Comparer cotisations et niveaux de remboursement.'],['Des choix compréhensibles','Lire ensemble les garanties et les conditions.']],explain:'Les bonnes garanties pour votre quotidien.',body:'Votre situation familiale et vos habitudes de soins guident la comparaison. Nous vous aidons à comprendre les niveaux de prise en charge pour choisir en connaissance de cause.',faq:[['Peut-on comparer mon contrat actuel ?','Oui. Votre tableau de garanties et votre cotisation constituent le point de départ de l’étude.'],['Est-il possible d’étudier une couverture familiale ?','Nous examinons les besoins de chaque personne à couvrir et les possibilités proposées par les contrats.'],['Comment choisir un niveau de garanties ?','Nous partons de vos besoins concrets et comparons les remboursements, les limites et le coût des différentes formules.']]},
{slug:'regroupement-credits',name:'Regroupement de crédits',short:'Regroupement de crédits',icon:'balance',sentence:'Rééquilibrez votre budget.',headline:'Une vision plus claire.<br>Un budget <em>mieux organisé.</em>',intro:'Faites étudier vos crédits et vos charges pour comprendre les possibilités de regroupement et leurs conséquences sur votre budget.',cta:'Faire étudier mon budget',benefits:[['Une vue d’ensemble','Faire le point sur vos crédits et vos charges.'],['Une étude chiffrée','Comparer mensualités, durée et coût total.'],['Un accompagnement personnel','Comprendre les options avant de décider.']],explain:'Regarder l’ensemble, avant de décider.',body:'Le regroupement de crédits s’étudie à partir de votre situation complète. Une mensualité réduite peut s’accompagner d’une durée plus longue et d’un coût total plus élevé.',faq:[['La baisse des mensualités réduit-elle le coût total ?','Pas nécessairement. Un allongement de durée peut augmenter le coût total. Ces éléments doivent être comparés ensemble.'],['Quels documents sont utiles pour une étude ?','Les informations sur vos crédits, vos revenus et vos charges permettent une première analyse.'],['L’étude garantit-elle une acceptation ?','Non. Une éventuelle offre reste soumise à l’analyse du dossier et aux conditions du prêteur.']]}
];
const rdv='<button class="button button-gold" data-book>Prendre rendez-vous '+icon('arrow')+'</button>';
const label=t=>`<p class="eyebrow"><span></span>${t}</p>`;
const brand=`<a class="brand" href="index.html" aria-label="GP Finances, accueil"><span class="brand-mark">GP</span><span>GP <b>FINANCES</b></span></a>`;
function header(active=''){return `${PROD?'':'<div class="preview-strip"><div class="container"><span><span class="status-dot"></span>Aperçu privé</span><span>Maquette du nouveau site GP Finances</span></div></div>'}<header class="site-header" id="header"><div class="container header-inner">${brand}<nav class="desktop-nav" aria-label="Navigation principale">${services.map(s=>`<a ${active===s.slug?'aria-current="page"':''} href="${s.slug}.html">${s.short}</a>`).join('')}<a href="index.html#conseils">Conseils</a></nav><div class="header-actions"><a class="header-phone" href="tel:+33651224213">06 51 22 42 13</a>${rdv}</div><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" aria-label="Ouvrir le menu">${icon('menu')}</button></div><nav class="services-strip" aria-label="Nos services"><div class="container">${services.map(s=>`<a ${active===s.slug?'aria-current="page"':''} href="${s.slug}.html">${s.short}</a>`).join('')}<a href="index.html#conseils">Conseils</a></div></nav><nav id="mobile-nav" class="mobile-nav" aria-label="Navigation mobile" hidden>${services.map(s=>`<a ${active===s.slug?'aria-current="page"':''} href="${s.slug}.html">${s.name}${icon('arrow')}</a>`).join('')}<a href="index.html#conseils">Conseils${icon('arrow')}</a>${rdv}</nav></header>`;}
function stats(){return `<section class="stats-section" aria-labelledby="stats-title"><div class="container">${label('La confiance, en chiffres')}<h2 id="stats-title">Des résultats qui parlent.</h2><div class="stats-grid"><div><p class="stat-number"><span data-stat="savings" data-live-savings>${data.savings}</span><span class="euro"> €</span></p><p>économisés par nos clients<br>en assurance emprunteur</p></div><div><p class="stat-number" data-stat="partners">${data.partners}</p><p>assureurs partenaires<br>pour comparer les solutions</p></div><div><p class="stat-number"><span data-stat="managed">${data.managed}</span><span class="percent"> %</span></p><p>des démarches<br>prises en charge</p></div></div></div></section>`;}
function process(){return `<section class="section process-section" id="methode"><div class="container">${label('Notre méthode')}<div class="section-heading"><h2>Je m’occupe de tout.</h2><p>Vous choisissez la solution. Je gère le reste.</p></div><div class="process-grid">${[['J’analyse','Votre situation, vos objectifs et vos contrats actuels.'],['Je compare','Les solutions du marché pour trouver celles qui vous correspondent.'],['Je gère','Les démarches, de l’étude jusqu’à la mise en place.']].map(([title,text],i)=>`<article class="process-step"><div class="step-top"><span class="step-number">0${i+1}</span><span class="step-line"></span></div><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></div></section>`;}
function comparison(type='assurance',tabs=false){return `<section class="section comparison-section" id="cas-concret"><div class="container comparison-layout"><div>${label('Avant / Après')}<h2>Moins de promesses.<br>Plus de concret.</h2><p class="section-intro">Des chiffres clairs pour mesurer l’intérêt d’une solution.</p>${tabs?'<div class="comparison-tabs" role="tablist" aria-label="Choisir un exemple"><button role="tab" aria-selected="true" data-comparison="assurance">Assurance emprunteur</button><button role="tab" aria-selected="false" data-comparison="per">PER</button></div>':''}<button class="text-link" data-book>Et dans ma situation ? ${icon('arrow')}</button></div><div class="comparison-card" data-comparison-card="${type}"></div></div></section>`;}
function testimonials(kind='mixed'){const allRows=kind==='per'?[['temoignage-dorothee.png','Dorothée','Plan Épargne Retraite','PER/temoignage-1-dorothee.mp4'],['temoignage-anaelle.png','Anaëlle','Plan Épargne Retraite','PER/temoignage-2-anaelle.mp4']]:[['temoignage-assurance.png','21 200 € économisés','Assurance emprunteur','Tem1.mp4'],['temoignage-dorothee.png','Dorothée','Plan Épargne Retraite','PER/temoignage-1-dorothee.mp4'],['temoignage-anaelle.png','Anaëlle','Plan Épargne Retraite','PER/temoignage-2-anaelle.mp4']];const rows=kind==='per'?allRows.reverse():kind==='assurance'?[allRows[0],['temoignage-dorothee-assurance.png','Dorothée','Assurance emprunteur · 17 000 € économisés','Tem2.mp4'],['temoignage-djian.png','Johanna','Assurance emprunteur · 14 100 € économisés','Tem4.mp4'],['temoignage-9000.png','John','Assurance emprunteur · 9 000 € économisés','Tem5.mp4']]:allRows;return `<section class="section testimonials-section" id="temoignages"><div class="container"><div class="section-heading heading-row"><div>${label('Ils nous font confiance')}<h2>Leurs mots, leur expérience.</h2></div><p>Découvrez les témoignages<br>de nos clients, en vidéo.</p></div><div class="testimonial-grid ${rows.length===2?'two-cards':rows.length===4?'four-cards':''}">${rows.map(([img,name,subject,video])=>`<button class="testimonial-card" data-video="https://gp-finances.fr/videos/${video}" data-video-title="Témoignage — ${name}" aria-label="Lire le témoignage : ${name}"><span class="testimonial-image"><img src="assets/${img}" alt="Aperçu du témoignage client" loading="lazy"><span class="video-shade"></span><span class="play-circle">${icon('play')}</span><span class="video-label">Témoignage client</span></span><span class="testimonial-info"><span>${kind==='per'?'':`<span class="small-caps">${subject}</span>`}<strong>${name}</strong></span>${icon('arrow')}</span></button>`).join('')}</div></div></section>`;}
function advisor(){return `<section class="section advisor-section" id="votre-courtier"><div class="container advisor-layout"><div class="advisor-photo"><img src="assets/gabriel-perbost.jpeg" alt="Gabriel Perbost dans son bureau" loading="lazy"><span class="photo-frame"></span></div><div class="advisor-copy">${label('Votre courtier')}<h2>Gabriel Perbost</h2><p class="advisor-role">Courtier indépendant</p><p class="section-intro">Un interlocuteur unique pour analyser votre situation, comparer les solutions et gérer vos démarches.</p><p class="advisor-note">Une relation directe. Des explications claires.<br>Un accompagnement à chaque étape.</p>${rdv}<p class="registration">GP FINANCES · ORIAS 23003789</p></div></div></section>`;}
function articles(){return `<section class="section articles-section" id="conseils"><div class="container"><div class="section-heading">${label('Pour y voir plus clair')}<h2>Nos derniers conseils</h2></div><div class="articles-grid"><a href="assurance-emprunteur.html#comprendre" class="article-card"><div class="article-art art-assurance">${icon('shield')}<span>Votre prêt.<br><b>Vos choix.</b></span></div><div class="article-body"><p class="small-caps">Assurance emprunteur · Repères</p><h3>Changer d’assurance sans changer de banque</h3><span class="text-link">Comprendre ${icon('arrow')}</span></div></a><a href="https://www.youtube.com/watch?v=CNFS4tn5538" target="_blank" rel="noopener" class="article-card article-video-card" aria-label="Lire la vidéo PER : 5 erreurs à éviter absolument sur YouTube (nouvel onglet)"><div class="article-art article-video"><img src="assets/per-5-erreurs.jpg" alt="" width="1280" height="720" loading="lazy"><span class="video-play-badge" aria-hidden="true">${icon('play')}</span></div><div class="article-body"><p class="small-caps">PER · Les conseils de Gabriel en vidéo</p><h3>PER : les 5 erreurs à éviter absolument</h3><span class="button button-gold video-cta">${icon('play')} Lire la vidéo ${icon('arrow')}</span><span class="video-platform-note">Regarder sur YouTube</span></div></a><a href="https://gp-finances.fr/lead-magnets/per/guide-per-7-erreurs.pdf" target="_blank" rel="noopener" class="article-card"><div class="article-art art-guide">${icon('book')}<span>Les bons réflexes<br><b>avant de choisir.</b></span></div><div class="article-body"><p class="small-caps">Épargne retraite · Guide pratique</p><h3>PER : les 7 erreurs à éviter</h3><span class="text-link">Découvrir le guide ${icon('arrow')}</span></div></a></div></div></section>`;}
function finalCTA(project=''){return `<section class="final-section"><div class="container final-inner">${label('Parlons de votre projet')}<h2>Et si on regardait ce que<br>vous pouvez <em>optimiser ?</em></h2><p>Un premier échange pour faire le point, simplement.</p><div class="cta-row">${rdv}<button class="button button-light" ${project?`data-project="${project}"`:'data-callback'}>Être rappelé ${icon('phone')}</button></div><p class="final-trust">Étude personnalisée <span>·</span> Sans engagement</p></div></section>`;}
function footer(){return `<footer class="footer"><div class="container"><div class="footer-top"><div>${brand}<p>Assurance, épargne et financement.<br>Un interlocuteur pour vos projets.</p></div><div class="footer-services"><span class="small-caps">Nos expertises</span>${services.map(s=>`<a href="${s.slug}.html">${s.name}</a>`).join('')}</div><div><span class="small-caps">Échangeons</span><a class="footer-phone" href="tel:+33651224213">06 51 22 42 13</a><a href="mailto:gabriel.perbost@gp-finances.fr">gabriel.perbost@gp-finances.fr</a><p>Issy-les-Moulineaux<br>Rendez-vous partout en France, en visio.</p></div></div><div class="footer-bottom"><p>© ${data.year} GP FINANCES · ORIAS 23003789 · RCS Nanterre 899 363 907</p><div class="footer-legal"><a href="mentions-legales.html">Mentions légales</a><a href="confidentialite.html">Politique de confidentialité</a><button type="button" class="footer-cookies" data-cookie-settings>Gérer mes cookies</button></div></div></div></footer><div class="mobile-cta">${rdv}<a class="button button-outline" href="tel:+33651224213" aria-label="Appeler GP Finances">${icon('phone')}</a></div>`;}
function dialogs(){return `<dialog id="booking-dialog" class="contact-dialog"><button class="dialog-close" aria-label="Fermer">${icon('close')}</button>${label('Votre projet')}<h2>Prenons le temps<br>d’en parler.</h2><p>Quel sujet souhaitez-vous aborder avec Gabriel ?</p><div class="booking-options">${services.map(s=>`<a href="${s.slug==='per'?'https://calendly.com/gabriel-perbost-gp-finances/votre-etude-d-optimisation-fiscale':s.slug==='assurance-emprunteur'?'https://calendly.com/gabriel-perbost/30min':'#rappel'}" ${s.slug==='per'||s.slug==='assurance-emprunteur'?'target="_blank" rel="noopener"':`data-project="${s.name}"`}>${icon(s.icon)}<span>${s.name}</span>${icon('arrow')}</a>`).join('')}</div><p class="dialog-note">Réservez un créneau pour votre assurance de prêt ou votre projet PER, ou demandez un rappel pour les autres sujets.</p></dialog><dialog id="callback-dialog" class="contact-dialog"><button class="dialog-close" aria-label="Fermer">${icon('close')}</button>${label('On vous rappelle')}<h2>Échangeons<br>sur votre projet.</h2><form id="callback-form"><label>Votre prénom<input name="prenom" autocomplete="given-name" required placeholder="Prénom"></label><label>Votre téléphone<input name="telephone" type="tel" autocomplete="tel" required pattern="[+0-9 ()\.\-]{10,20}" placeholder="06 00 00 00 00"></label><label>Votre projet<select name="projet">${services.map(s=>`<option>${s.name}</option>`).join('')}</select></label><button class="button button-gold" type="submit">Demander un rappel ${icon('arrow')}</button><label class="consent-line"><input type="checkbox" name="consent" required><span>J’accepte d’être rappelé(e) par GP FINANCES au sujet de mon projet et que mon prénom et mon téléphone soient utilisés à cette seule fin. <a href="confidentialite.html">Politique de confidentialité</a></span></label><p class="dialog-note">Vous serez rappelé(e) au plus vite. Sans engagement.</p><p id="callback-result" class="form-result" role="status" hidden></p></form></dialog><dialog id="video-dialog" class="video-dialog"><button class="dialog-close" aria-label="Fermer la vidéo">${icon('close')}</button><h2 class="sr-only" id="video-title">Témoignage client</h2><video controls playsinline preload="none" aria-labelledby="video-title"></video></dialog>`;}
function shell(title,desc,body,active=''){return `<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${PROD?'<meta name="robots" content="index,follow">':'<meta name="robots" content="noindex,nofollow">'}<meta name="description" content="${desc}"><meta name="theme-color" content="#0d1f3c"><title>${title} | GP Finances${PROD?'':' · Maquette'}</title><link rel="icon" href="assets/favicon.png"><link rel="stylesheet" href="assets/fonts.css"><link rel="stylesheet" href="styles.css?v=20260924p"><link rel="stylesheet" href="social-proof.css?v=20260924p"><script src="live-counter.js?v=20260924p" defer></script><script src="consent-tracking.js?v=20260924p" defer></script><script src="app.js" defer></script><script src="reviews-carousel.js" defer></script>${active==='per'?'<link rel="stylesheet" href="per-simulator.css"><script src="per-calculator.js" defer></script><script src="per-projection.js" defer></script><script src="per-profile.js" defer></script><script src="per-simulator.js" defer></script>':''}${active==='assurance-vie'?'<link rel="stylesheet" href="life-simulator.css"><script src="life-calculator.js" defer></script><script src="life-simulator.js" defer></script>':''}${active==='assurance-emprunteur'?'<link rel="stylesheet" href="insurance-simulator.css?v=20260924p"><script src="borrower-references.js?v=20260924p" defer></script><script src="insurance-quote.js?v=20260924p" defer></script>':''}</head><body${active==='assurance-emprunteur'?' data-service="assurance-emprunteur"':''}><a class="skip-link" href="#main">Aller au contenu</a>${header(active)}<main id="main">${body}</main>${footer()}${dialogs()}</body></html>`;}
const trust=`<ul class="trust-list">${['Courtier indépendant','Étude personnalisée','Sans engagement'].map(t=>`<li>${icon('check')}${t}</li>`).join('')}</ul>`;
const home=`<section class="hero"><div class="container hero-layout"><div class="hero-copy">${label('GP FINANCES · Courtier indépendant')}<h1>Vos <span class="hero-finances"><span class="hero-finances-f">f</span>inances</span><br>méritent <em>mieux.</em></h1><p class="hero-description">Assurance, épargne, fiscalité : nous trouvons les solutions adaptées à votre situation et nous nous occupons des démarches.</p><div class="cta-row"><a class="button button-gold" href="#solutions">Découvrir nos solutions ${icon('arrow')}</a><button class="button button-outline" data-book>Prendre rendez-vous</button></div>${trust}${proof.heroProof()}</div><div class="hero-visual"><div class="hero-portrait"><img src="assets/gabriel-perbost.jpeg" alt="Gabriel Perbost, courtier indépendant GP Finances" fetchpriority="high"><span class="photo-frame"></span></div><div class="portrait-caption"><span class="caption-line"></span><div><strong>Gabriel Perbost</strong><span>Votre courtier. Votre interlocuteur.</span></div></div><span class="visual-wordmark" aria-hidden="true">GP</span></div></div></section>${proof.ticker()}${proof.trustBar()}${proof.carousel()}<section class="section services-section" id="solutions"><div class="container"><div class="section-heading">${label('Nos expertises')}<h2>Là où nous pouvons<br>vous faire gagner.</h2></div><div class="services-grid">${services.map(s=>`<a class="service-card" href="${s.slug}.html"><span class="service-icon">${icon(s.icon)}</span><h3>${s.name}</h3><p>${s.sentence}</p><span class="text-link">Découvrir ${icon('arrow')}</span></a>`).join('')}</div></div></section>${stats()}${process()}${comparison('assurance',true)}${testimonials()}${advisor()}${articles()}${finalCTA()}`;
fs.writeFileSync(path.join(OUT,'index.html'),shell('Vos finances méritent mieux','GP Finances : assurance emprunteur, épargne retraite, assurance-vie, prévoyance, mutuelle et regroupement de crédits. Courtier indépendant.',home));
for(const s of services){
 const isPER=s.slug==='per',isInsurance=s.slug==='assurance-emprunteur',isLife=s.slug==='assurance-vie';
 const visual=isInsurance?`<span class="small-caps">Cas client · Assurance emprunteur</span><div class="service-number">21 200<span> €</span></div><p>d’économie sur le coût total<br>de l’assurance de prêt</p><div class="mini-bars"><span>Avant <b>32 710 €</b></span><i></i><span>Après GP FINANCES <b>11 510 €</b></span><i></i></div><p class="fine-print">Exemple issu d’un dossier client. Le résultat dépend de chaque situation.</p>`:isPER?perHero:isLife?lifeHero:`<span class="service-icon">${icon(s.icon)}</span><h2>${isLife?'Votre épargne.<br>Votre horizon.':'Votre situation.<br>Votre solution.'}</h2><p>${isLife?'Vos objectifs, vos besoins de disponibilité et votre profil guident chaque choix.':'Un échange personnel pour identifier vos priorités et comparer les possibilités.'}</p><div class="mini-advisor"><img src="assets/gabriel-perbost.jpeg" alt=""><span>Gabriel Perbost<small>Courtier indépendant</small></span></div>`;
 const body=`<section class="service-hero"><div class="container"><a href="index.html#solutions" class="breadcrumb">Accueil <span>/</span> ${s.name}</a><div class="service-hero-layout"><div class="service-hero-copy">${label(s.name)}<h1>${s.headline}</h1><p class="hero-description">${s.intro}</p><div class="cta-row">${isPER?`<a class="button button-gold" href="#simuler">Personnaliser ma simulation ${icon('arrow')}</a>`:isInsurance?`<a class="button button-gold" href="#simuler-assurance">Estimer mes économies ${icon('arrow')}</a><button class="text-link" data-project="Assurance emprunteur">Demander une étude ${icon('arrow')}</button>`:`<button class="button button-gold" ${isLife?`data-project="${s.name}"`:'data-book'}>${s.cta} ${icon('arrow')}</button>`}</div><p class="quiet-trust">${icon('check')}Étude personnalisée · Sans engagement</p>${proof.heroProof(s.slug)}</div><aside class="service-hero-card ${isInsurance?'numbers-card':isLife?'life-hero-card':isPER?'per-hero-card':''}">${visual}</aside></div></div></section>${proof.ticker()}${isPER?perSimulator:''}${isLife?lifeSimulator:''}${isInsurance?insuranceSimulator+testimonials('assurance'):''}<section class="benefits-section"><div class="container benefits-grid">${s.benefits.map(([title,copy],i)=>`<article><span class="service-icon">${icon([s.icon,'person','check'][i])}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div></section>${isInsurance?stats():''}<section class="section" id="comprendre"><div class="container simple-explainer">${label('Les choses, simplement')}<h2>${s.explain}</h2><p class="section-intro">${s.body}</p>${isPER?'<p class="fine-print">L’avantage fiscal dépend de votre situation. Les unités de compte présentent un risque de perte en capital.</p>':isLife?'<p class="fine-print">Les unités de compte présentent un risque de perte en capital. Le choix des supports dépend de votre profil et de votre horizon de placement.</p>':''}</div></section>${isInsurance?comparison('assurance'):''}${isPER?testimonials('per'):''}${proof.carousel(s.slug)}${advisor()}${process()}<section class="section faq-section"><div class="container faq-layout"><div>${label('Vos questions')}<h2>Parlons-en<br>simplement.</h2><p>Un point reste à éclaircir ?<br>Je suis là pour vous répondre.</p><button class="text-link" ${isLife?`data-project="${s.name}"`:'data-book'}>Poser ma question ${icon('arrow')}</button></div><div class="faq-list">${s.faq.map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>${finalCTA(isLife?s.name:'')}`;
 fs.writeFileSync(path.join(OUT,s.slug+'.html'),shell(s.name,s.sentence,body,s.slug));
}

function legalPage(file,title,desc,inner){
 const body=`<section class="section legal-page"><div class="container legal-inner"><a href="index.html" class="breadcrumb">Accueil <span>/</span> ${title}</a><h1>${title}</h1><p class="legal-updated">Dernière mise à jour : 24 septembre 2026</p>${inner}</div></section>`;
 fs.writeFileSync(path.join(OUT,file),shell(title,desc,body,''));
}
legalPage('mentions-legales.html','Mentions légales','Mentions légales du site gp-finances.fr : éditeur, immatriculations, hébergement, propriété intellectuelle.',`
<h2>Éditeur du site</h2>
<p><strong>GP FINANCES</strong>, courtier en assurance et en opérations de banque.<br>Représentant : Gabriel Perbost.<br>RCS Nanterre 899 363 907.<br>Siège : 24 rue du Gouverneur Général Éboué, 92130 Issy-les-Moulineaux.<br>Téléphone : <a href="tel:+33651224213">06 51 22 42 13</a> · E-mail : <a href="mailto:gabriel.perbost@gp-finances.fr">gabriel.perbost@gp-finances.fr</a><br>Directeur de la publication : Gabriel Perbost.</p>
<h2>Immatriculation et contrôle</h2>
<p>Intermédiaire immatriculé à l’ORIAS sous le n° 23003789 (courtier en assurance et courtier en opérations de banque et services de paiement). Vous pouvez vérifier cette immatriculation sur <a href="https://www.orias.fr" target="_blank" rel="noopener">www.orias.fr</a>. Le cabinet est référencé à l’annuaire de la <a href="https://www.cncef.org/annuaire/perbost-gabriel/" target="_blank" rel="noopener">CNCEF</a>.</p>
<p>Autorité de contrôle : Autorité de contrôle prudentiel et de résolution (ACPR), 4 place de Budapest, CS 92459, 75436 Paris Cedex 09.</p>
<h2>Hébergement</h2>
<p>Le site est hébergé par Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, États-Unis.</p>
<h2>Nature des informations</h2>
<p>Les estimations fournies par les simulateurs sont indicatives et non contractuelles. Elles ne constituent ni un devis ni une offre : le tarif définitif dépend de l’acceptation du dossier par l’assureur et de l’équivalence de garanties exigée par votre banque. Les résultats passés ou les exemples chiffrés ne préjugent pas de résultats futurs. Les unités de compte des contrats d’assurance-vie et de PER présentent un risque de perte en capital.</p>
<h2>Propriété intellectuelle</h2>
<p>Les textes, images, vidéos, logos et éléments graphiques du site sont la propriété de GP FINANCES ou utilisés avec l’autorisation de leurs titulaires. Toute reproduction sans autorisation écrite est interdite. Les témoignages vidéo sont publiés avec l’accord des clients concernés.</p>
<h2>Liens externes</h2>
<p>Le site contient des liens vers des services tiers (Google, Calendly, YouTube). GP FINANCES n’est pas responsable de leur contenu ni de leurs pratiques de confidentialité.</p>
<h2>Vos données personnelles</h2>
<p>Consultez notre <a href="confidentialite.html">politique de confidentialité</a> pour connaître les données traitées, leur durée de conservation et vos droits.</p>`);
legalPage('confidentialite.html','Politique de confidentialité','Comment GP FINANCES traite vos données personnelles : finalités, base légale, destinataires, durées, cookies et droits.',`
<p class="legal-lead">Cette politique explique quelles données sont collectées lorsque vous utilisez ce site, pourquoi, avec qui elles sont partagées, combien de temps elles sont conservées et comment exercer vos droits.</p>
<h2>1. Responsable du traitement</h2>
<p>GP FINANCES, représenté par Gabriel Perbost, 24 rue du Gouverneur Général Éboué, 92130 Issy-les-Moulineaux. Contact : <a href="mailto:gabriel.perbost@gp-finances.fr">gabriel.perbost@gp-finances.fr</a>.</p>
<h2>2. Les données que nous traitons</h2>
<h3>Simulateur d’assurance emprunteur</h3>
<p>Le simulateur ne demande <strong>ni votre nom, ni votre adresse e-mail, ni votre téléphone</strong>. Il traite en revanche des données de profil, nécessaires pour calculer une estimation : civilité, date de naissance, situation professionnelle et profession, code postal et ville, nature du projet, capital restant dû, durée restante, taux du prêt, quotité assurée, autres crédits assurés, ainsi que vos réponses sur le tabagisme et sur certaines activités professionnelles ou sportives à risque. Les réponses sur le tabagisme et les activités à risque se rapportent à votre santé : elles ne sont traitées qu’avec votre <strong>consentement explicite</strong>, recueilli par la case à cocher avant l’envoi. Ces données peuvent concerner un second emprunteur si vous en indiquez un.</p>
<h3>Demande de rappel</h3>
<p>Si vous demandez à être rappelé(e), nous traitons votre prénom et votre numéro de téléphone (et éventuellement votre e-mail) pour vous recontacter.</p>
<h3>Autres simulateurs (PER, assurance-vie)</h3>
<p>Ces simulateurs calculent leur résultat directement dans votre navigateur. Les chiffres saisis ne sont pas envoyés à nos serveurs.</p>
<h3>Mesure d’audience</h3>
<p>Avec votre accord uniquement, nous utilisons des outils de mesure d’audience (Google Analytics, et Meta si activé) : pages consultées, clics sur les menus, sur le téléphone ou les rendez-vous, lancement d’une simulation, lecture d’une vidéo. Ces informations sont statistiques et ne servent pas à vous identifier.</p>
<h2>3. Pourquoi (finalités) et sur quelle base légale</h2>
<table class="legal-table"><thead><tr><th>Finalité</th><th>Base légale</th></tr></thead><tbody>
<tr><td>Établir votre estimation d’assurance emprunteur</td><td>Mesures précontractuelles prises à votre demande ; consentement explicite pour les données de santé (art. 6.1.b et 9.2.a du RGPD)</td></tr>
<tr><td>Nous informer de chaque simulation réalisée, afin d’étudier les demandes et de pouvoir vous accompagner si vous prenez contact</td><td>Intérêt légitime de GP FINANCES à suivre son activité (art. 6.1.f)</td></tr>
<tr><td>Vous rappeler après une demande de rappel</td><td>Votre consentement et les mesures précontractuelles (art. 6.1.a et 6.1.b)</td></tr>
<tr><td>Mesurer l’audience et améliorer le site</td><td>Votre consentement (cookies)</td></tr>
<tr><td>Respecter nos obligations légales (courtage, lutte contre le blanchiment)</td><td>Obligation légale (art. 6.1.c)</td></tr>
</tbody></table>
<h2>4. Qui reçoit vos données</h2>
<ul><li><strong>GP FINANCES</strong> : chaque simulation est transmise par e-mail sécurisé à l’adresse du cabinet.</li><li><strong>Les assureurs partenaires et leur plateforme de tarification</strong> : seules les données de profil nécessaires au calcul du tarif leur sont transmises, sans aucune donnée d’identité.</li><li><strong>Nos prestataires techniques</strong> : hébergeur du site (Vercel), messagerie (IONOS), agenda de rendez-vous (Calendly) lorsque vous l’utilisez.</li><li><strong>Google et Meta</strong>, pour la mesure d’audience, uniquement si vous avez accepté les cookies.</li></ul>
<p>Certains prestataires sont situés aux États-Unis. Ces transferts sont encadrés par des garanties appropriées (clauses contractuelles types de la Commission européenne ou cadre de protection des données UE–États-Unis).</p>
<h2>5. Combien de temps</h2>
<ul><li>Simulations d’assurance emprunteur : <strong>12 mois</strong> maximum, puis suppression.</li><li>Demandes de rappel : le temps nécessaire au traitement de la demande, puis <strong>3 ans</strong> après le dernier contact si aucune relation contractuelle ne s’engage.</li><li>Clients : pendant la relation contractuelle, puis pendant les durées légales de prescription et de conservation.</li><li>Choix sur les cookies : <strong>6 mois</strong>, puis nouvelle demande. Données de mesure d’audience : 14 mois maximum.</li></ul>
<h2>6. Cookies et traceurs</h2>
<p>Aucun cookie de mesure d’audience ni de publicité n’est déposé avant votre choix. Le bandeau vous propose « Tout accepter » ou « Tout refuser », avec la même facilité. Refuser n’a aucune conséquence sur votre navigation. Vous pouvez modifier votre choix à tout moment avec le lien « Gérer mes cookies » en bas de chaque page. Le seul élément conservé dans votre navigateur avant tout choix est votre décision elle-même (stockage local), nécessaire pour ne pas vous redemander à chaque page.</p>
<h2>7. Vos droits</h2>
<p>Vous disposez d’un droit d’accès, de rectification, d’effacement, de limitation, d’opposition et de portabilité, du droit de retirer votre consentement à tout moment (le retrait ne remet pas en cause les traitements passés) et du droit de définir des directives sur le sort de vos données après votre décès. Pour les exercer, écrivez à <a href="mailto:gabriel.perbost@gp-finances.fr">gabriel.perbost@gp-finances.fr</a>. Comme le simulateur ne collecte pas votre identité, indiquez-nous la date et l’heure de votre simulation et les principales données saisies afin que nous puissions la retrouver. Une réponse vous est apportée dans un délai d’un mois.</p>
<p>Si vous estimez, après nous avoir contactés, que vos droits ne sont pas respectés, vous pouvez introduire une réclamation auprès de la CNIL : <a href="https://www.cnil.fr" target="_blank" rel="noopener">www.cnil.fr</a>.</p>
<h2>8. Sécurité</h2>
<p>Les échanges avec le site sont chiffrés (HTTPS). Le simulateur limite le nombre de demandes, filtre les données reçues et ne les transmet aux partenaires que sous une forme strictement nécessaire. Les accès aux boîtes et outils du cabinet sont protégés.</p>
<h2>9. Modifications</h2>
<p>Cette politique peut évoluer. La date de dernière mise à jour figure en haut de cette page.</p>`);
if(OUT===ROOT)fs.writeFileSync(path.join(ROOT,'chiffres.json'),JSON.stringify(data,null,2));
console.log(`Generated homepage and ${services.length} service previews.`);
